[project]
name = "deal-data-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "mt5manager>=5.0.4874",
    "python-dotenv>=1.0.1",
]
